CARS = [
    {
        "id": 1,
        "brand": "BYD",
        "model": "Atto 3",
        "year": 2024,
        "price": 150000,
        "fuel_type": "ev",
        "body_type": "suv",
        "seats": 5,
        "range_km": 420,
        "horsepower": 201,
        "safety_score": 86,
        "reliability_score": 78,
        "comfort_score": 84,
        "performance_score": 80,
        "tech_score": 92,
        "maintenance_cost_score": 88,
        "description": "A practical electric SUV with strong technology features and good city usability."
    },
    {
        "id": 2,
        "brand": "Tesla",
        "model": "Model 3",
        "year": 2024,
        "price": 190000,
        "fuel_type": "ev",
        "body_type": "sedan",
        "seats": 5,
        "range_km": 510,
        "horsepower": 283,
        "safety_score": 92,
        "reliability_score": 76,
        "comfort_score": 86,
        "performance_score": 94,
        "tech_score": 98,
        "maintenance_cost_score": 82,
        "description": "A high-tech electric sedan with strong performance and long range."
    },
    {
        "id": 3,
        "brand": "Toyota",
        "model": "Corolla Cross Hybrid",
        "year": 2024,
        "price": 140000,
        "fuel_type": "hybrid",
        "body_type": "suv",
        "seats": 5,
        "range_km": 800,
        "horsepower": 121,
        "safety_score": 88,
        "reliability_score": 94,
        "comfort_score": 82,
        "performance_score": 65,
        "tech_score": 75,
        "maintenance_cost_score": 90,
        "description": "A reliable hybrid SUV with good practicality, safety, and fuel economy."
    },
    {
        "id": 4,
        "brand": "Honda",
        "model": "Civic",
        "year": 2024,
        "price": 145000,
        "fuel_type": "petrol",
        "body_type": "sedan",
        "seats": 5,
        "range_km": 650,
        "horsepower": 180,
        "safety_score": 86,
        "reliability_score": 88,
        "comfort_score": 83,
        "performance_score": 82,
        "tech_score": 78,
        "maintenance_cost_score": 82,
        "description": "A sporty and reliable sedan with good comfort and daily usability."
    },
    {
        "id": 5,
        "brand": "Toyota",
        "model": "Hilux",
        "year": 2024,
        "price": 135000,
        "fuel_type": "diesel",
        "body_type": "pickup",
        "seats": 5,
        "range_km": 750,
        "horsepower": 201,
        "safety_score": 80,
        "reliability_score": 96,
        "comfort_score": 72,
        "performance_score": 78,
        "tech_score": 68,
        "maintenance_cost_score": 86,
        "description": "A durable pickup truck suitable for work, off-road use, and long-term reliability."
    },
    {
        "id": 6,
        "brand": "MG",
        "model": "MG4 EV",
        "year": 2024,
        "price": 130000,
        "fuel_type": "ev",
        "body_type": "hatchback",
        "seats": 5,
        "range_km": 435,
        "horsepower": 201,
        "safety_score": 84,
        "reliability_score": 74,
        "comfort_score": 78,
        "performance_score": 82,
        "tech_score": 86,
        "maintenance_cost_score": 88,
        "description": "A good-value electric hatchback with solid range and modern features."
    }
]